### ISSUE TITLE
TypeError: 'Exception' object is not iterable

### ISSUE THREAD

**Issue by willkg** [rpappalax/antenna-loadtests#10]
When I try to run master tip against Antenna running on my local machine, I get this:

```
(M=bc78b) ~/mozilla/socorro-zero/antenna-loadtests> make test -e URL_SERVER=http://localhost:8000/submit
env LDFLAGS="-L/lib" \
    CFLAGS="-I/include" \
    /home/willkg/mozilla/socorro-zero/antenna-loadtests/venv/bin/pip3 install cryptography
Requirement already satisfied: cryptography in ./venv/lib/python3.5/site-packages
Requirement already satisfied: idna>=2.0 in ./venv/lib/python3.5/site-packages (from cryptography)
Requirement already satisfied: pyasn1>=0.1.8 in ./venv/lib/python3.5/site-packages (from cryptography)
Requirement already satisfied: setuptools>=11.3 in ./venv/lib/python3.5/site-packages (from cryptography)
Requirement already satisfied: cffi>=1.4.1 in ./venv/lib/python3.5/site-packages (from cryptography)
Requirement already satisfied: six>=1.4.1 in ./venv/lib/python3.5/site-packages (from cryptography)
Requirement already satisfied: pycparser in ./venv/lib/python3.5/site-packages (from cffi>=1.4.1->cryptography)
/home/willkg/mozilla/socorro-zero/antenna-loadtests/venv/bin/pip3 install -r requirements.txt
Collecting https://github.com/tarekziade/ailoads/archive/master.zip (from -r requirements.txt (line 4))
  Downloading https://github.com/tarekziade/ailoads/archive/master.zip
     / 40kB 1.1MB/s
Requirement already satisfied: six in ./venv/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: requests in ./venv/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: flake8 in ./venv/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Collecting aiohttp (from molotov==0.4->-r requirements.txt (line 4))
  Downloading aiohttp-1.2.0-cp35-cp35m-manylinux1_x86_64.whl (155kB)
    100% |████████████████████████████████| 163kB 1.6MB/s 
Requirement already satisfied: statsd in ./venv/lib/python3.5/site-packages (from molotov==0.4->-r requirements.txt (line 4))
Collecting urwid (from molotov==0.4->-r requirements.txt (line 4))
  Downloading urwid-1.3.1.tar.gz (588kB)
    100% |████████████████████████████████| 593kB 1.9MB/s 
Collecting humanize (from molotov==0.4->-r requirements.txt (line 4))
  Downloading humanize-0.5.1.tar.gz
Collecting redis (from molotov==0.4->-r requirements.txt (line 4))
  Downloading redis-2.10.5-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 2.9MB/s 
Requirement already satisfied: pycodestyle<2.3.0,>=2.0.0 in ./venv/lib/python3.5/site-packages (from flake8->-r requirements.txt (line 3))
Requirement already satisfied: pyflakes!=1.2.0,!=1.2.1,!=1.2.2,<1.4.0,>=0.8.1 in ./venv/lib/python3.5/site-packages (from flake8->-r requirements.txt (line 3))
Requirement already satisfied: mccabe<0.6.0,>=0.5.0 in ./venv/lib/python3.5/site-packages (from flake8->-r requirements.txt (line 3))
Collecting chardet (from aiohttp->molotov==0.4->-r requirements.txt (line 4))
  Downloading chardet-2.3.0.tar.gz (164kB)
    100% |████████████████████████████████| 174kB 6.7MB/s 
Collecting multidict>=2.1.4 (from aiohttp->molotov==0.4->-r requirements.txt (line 4))
  Downloading multidict-2.1.4-cp35-cp35m-manylinux1_x86_64.whl (357kB)
    100% |████████████████████████████████| 358kB 2.6MB/s 
Collecting async-timeout>=1.1.0 (from aiohttp->molotov==0.4->-r requirements.txt (line 4))
  Downloading async_timeout-1.1.0-py3-none-any.whl
Collecting yarl>=0.8.1 (from aiohttp->molotov==0.4->-r requirements.txt (line 4))
  Downloading yarl-0.8.1-cp35-cp35m-manylinux1_x86_64.whl (137kB)
    100% |████████████████████████████████| 143kB 2.2MB/s 
Building wheels for collected packages: urwid, humanize, chardet
  Running setup.py bdist_wheel for urwid ... done
  Stored in directory: /home/willkg/.cache/pip/wheels/e7/bb/9d/d7f7fcc9b3aeae20cf4685667635002415629e6395ff2dda7d
  Running setup.py bdist_wheel for humanize ... done
  Stored in directory: /home/willkg/.cache/pip/wheels/d4/80/38/cfbfd95752f71f3812505b948b43383ddc99eedf835fc13b09
  Running setup.py bdist_wheel for chardet ... done
  Stored in directory: /home/willkg/.cache/pip/wheels/28/8c/bf/a69199bd4901d84e13362f95a9ea7bc9a691fed2d655a90bc4
Successfully built urwid humanize chardet
Installing collected packages: chardet, multidict, async-timeout, yarl, aiohttp, urwid, humanize, redis, molotov
  Running setup.py install for molotov ... done
Successfully installed aiohttp-1.2.0 async-timeout-1.1.0 chardet-2.3.0 humanize-0.5.1 molotov-0.4 multidict-2.1.4 redis-2.10.5 urwid-1.3.1 yarl-0.8.1
bash -c "URL_SERVER=http://localhost:8000/submit /home/willkg/mozilla/socorro-zero/antenna-loadtests/venv/bin/ailoads -v -d 30"
[th]Traceback (most recent call last):
  File "/home/willkg/mozilla/socorro-zero/antenna-loadtests/venv/bin/ailoads", line 11, in <module>
    load_entry_point('ailoads==0.1', 'console_scripts', 'ailoads')()
  File "/home/willkg/mozilla/socorro-zero/antenna-loadtests/venv/lib/python3.5/site-packages/ailoads/run.py", line 71, in main
    return run(args)
  File "/home/willkg/mozilla/socorro-zero/antenna-loadtests/venv/lib/python3.5/site-packages/ailoads/run.py", line 85, in run
    for ok, failed in res:
TypeError: 'Exception' object is not iterable
Makefile:56: recipe for target 'test' failed
make: *** [test] Error 1
2 (M=bc78b) ~/mozilla/socorro-zero/antenna-loadtests> 
```

Am I doing something wrong? If not, any idea what's going on.

**Comment by m8ttyB** [comment]
@rpappalax this appears to be what we saw when running the `docker-run` command yesterday, any ideas?

**Comment by willkg** [comment]
I did some poking around and my TypeError is from the fact that all the tests are set to run never. Changing any of them from 0 to a non-zero number causes tests to run.

**Comment by m8ttyB** [comment]
👍 oy.

**Comment by m8ttyB** [comment]
remedied in #11

**Comment by rpappalax** [comment]
thanks, @willkg I'll add a conditional to molotov to ensure that scenario weights are > 0

**Comment by tarekziade** [comment]
@rpappalax  @willkg thanks for reporting, it's now fixed in molotov.
